### train_x,train_y, test_x, test_y 만들기

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train=pd.read_csv('data/train_onehot.csv')
test=pd.read_csv('data/test_onehot.csv')

In [ ]:
train_x=train.drop('credit',axis=1)
train_y=train['credit']

In [ ]:
print(train_x.shape)
print(train_y.shape)

(26457, 58)
(26457,)


In [ ]:
test_x=test

In [ ]:
a=pd.concat([train,test],axis = 0)
b=a[-10000:]
test_y=b['credit']

In [ ]:
print(test_x.shape)
print(test_y.shape)

(10000, 58)
(10000,)


randomforest이용하기

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier()

In [ ]:
clf.fit(train_x,train_y)

RandomForestClassifier()

In [ ]:
train_proba=clf.predict_proba(train_x)
train_proba

array([[0.03, 0.69, 0.28],
       [0.13, 0.61, 0.26],
       [0.02, 0.03, 0.95],
       ...,
       [0.05, 0.09, 0.86],
       [0.01, 0.15, 0.84],
       [0.04, 0.06, 0.9 ]])

In [ ]:
np.argmax(train_proba, axis=1)[:10]

array([1, 1, 2, 0, 2, 1, 2, 0, 2, 2], dtype=int64)

In [ ]:
clf.predict_proba(test_x)

array([[0.1 , 0.29, 0.61],
       [0.19, 0.45, 0.36],
       [0.12, 0.09, 0.79],
       ...,
       [0.01, 0.03, 0.96],
       [0.18, 0.52, 0.3 ],
       [0.1 , 0.33, 0.57]])

In [ ]:
sample_submission=pd.read_csv('data/sample_submission.csv')
sample_submission

index  0  1  2
0     26457  0  0  0
1     26458  0  0  0
2     26459  0  0  0
3     26460  0  0  0
4     26461  0  0  0
...     ... .. .. ..
9995  36452  0  0  0
9996  36453  0  0  0
9997  36454  0  0  0
9998  36455  0  0  0
9999  36456  0  0  0

[10000 rows x 4 columns]

In [ ]:
sample_submission.iloc[:,1:]=clf.predict_proba(test_x)

In [ ]:
sample_submission

index     0     1     2
0     26457  0.10  0.29  0.61
1     26458  0.19  0.45  0.36
2     26459  0.12  0.09  0.79
3     26460  0.24  0.09  0.67
4     26461  0.18  0.15  0.67
...     ...   ...   ...   ...
9995  36452  0.06  0.18  0.76
9996  36453  0.50  0.28  0.22
9997  36454  0.01  0.03  0.96
9998  36455  0.18  0.52  0.30
9999  36456  0.10  0.33  0.57

[10000 rows x 4 columns]

In [ ]:
sample_submission.to_csv('submission_RF.csv',index=False)